import type { MusicPayload } from "@watchme/shared";

const descriptions: Record<string, string> = {
  telegram: "正在 Telegram 上冲浪~",
  qq: "正在 QQ 上水群~",
  tim: "正在 TIM 上水群~",
  wechat: "正在微信上聊天~",
  discord: "正在 Discord 灌水~",
  line: "正在 Line 上聊天~",
  "enterprise wechat": "正在企业微信办公~",
  dingtalk: "正在钉钉办公~",
  feishu: "正在飞书办公~",
  slack: "正在 Slack 摸鱼~",
  chatgpt: "正在和 ChatGPT 对话~",
  claude: "正在和 Claude 对话~",
  gemini: "正在和 Gemini 对话~",
  copilot: "正在和 Copilot 对话~",
  deepseek: "正在和 DeepSeek 对话~",
  kimi: "正在和 Kimi 对话~",
  "google chrome": "正在用 Chrome 逛网页~",
  "microsoft edge": "正在用 Edge 逛网页~",
  firefox: "正在用 Firefox 逛网页~",
  safari: "正在用 Safari 逛网页~",
  opera: "正在用 Opera 逛网页~",
  arc: "正在用 Arc 逛网页~",
  brave: "正在用 Brave 逛网页~",
  vivaldi: "正在用 Vivaldi 逛网页~",
  "vs code": "正在 VS Code 里写代码~",
  cursor: "正在 Cursor 里写代码~",
  "visual studio": "正在 Visual Studio 里写代码~",
  "intellij idea": "正在 IDEA 里写代码~",
  pycharm: "正在 PyCharm 里写代码~",
  webstorm: "正在 WebStorm 里写代码~",
  goland: "正在 GoLand 里写代码~",
  rider: "正在 Rider 里写代码~",
  datagrip: "正在 DataGrip 查数据库~",
  "android studio": "正在 Android Studio 里写代码~",
  sublime: "正在 Sublime 里写代码~",
  windsurf: "正在 Windsurf 里写代码~",
  zed: "正在 Zed 里写代码~",
  vim: "正在 Vim 里写代码~",
  neovim: "正在 Neovim 里写代码~",
  emacs: "正在 Emacs 里写代码~",
  docker: "正在 Docker 里折腾容器~",
  postman: "正在 Postman 调接口~",
  dbeaver: "正在 DBeaver 查数据库~",
  navicat: "正在 Navicat 查数据库~",
  insomnia: "正在 Insomnia 调接口~",
  wireshark: "正在 Wireshark 抓包~",
  fiddler: "正在 Fiddler 抓包~",
  charles: "正在 Charles 抓包~",
  spotify: "正在 Spotify 听歌~",
  "qq music": "正在 QQ 音乐听歌~",
  "netease cloud music": "正在网易云听歌~",
  "apple music": "正在 Apple Music 听歌~",
  kugou: "正在酷狗听歌~",
  kuwo: "正在酷我听歌~",
  foobar2000: "正在用 foobar2000 听歌~",
  figma: "正在 Figma 里做设计~",
  sketch: "正在 Sketch 里做设计~",
  photoshop: "正在 Photoshop 里修图~",
  illustrator: "正在 Illustrator 里画图~",
  premiere: "正在 Premiere 里剪视频~",
  "after effects": "正在 AE 里做特效~",
  blender: "正在 Blender 里做 3D~",
  c4d: "正在 C4D 里做 3D~",
  gimp: "正在 GIMP 里修图~",
  canva: "正在 Canva 里做设计~",
  lightroom: "正在 Lightroom 里修照片~",
  krita: "正在 Krita 里画画~",
  "file explorer": "正在翻文件夹找东西~",
  finder: "正在翻文件夹找东西~",
  "windows terminal": "正在命令行里敲命令~",
  powershell: "正在 PowerShell 里敲命令~",
  "command prompt": "正在命令行里敲命令~",
  terminal: "正在命令行里敲命令~",
  steam: "正在 Steam 玩游戏~",
  epic: "正在 Epic 玩游戏~",
  minecraft: "正在 Minecraft 里挖矿~",
  valorant: "正在 VALORANT 对枪~",
  cs2: "正在 CS2 对枪~",
  apex: "正在 Apex 里跳伞~",
  roblox: "正在 Roblox 里玩~",
  vlc: "正在 VLC 看视频~",
  potplayer: "正在 PotPlayer 看视频~",
  mpv: "正在 mpv 看视频~",
  bilibili: "正在 B 站划水~",
  youtube: "正在 YouTube 看视频~",
  netflix: "正在 Netflix 追剧~",
  twitch: "正在 Twitch 看直播~",
  douyu: "正在斗鱼看直播~",
  huya: "正在虎牙看直播~",
  word: "正在 Word 里写文档~",
  excel: "正在 Excel 里算数据~",
  powerpoint: "正在做 PPT~",
  onenote: "正在 OneNote 里记笔记~",
  notion: "正在 Notion 里记笔记~",
  obsidian: "正在 Obsidian 里记笔记~",
  typora: "正在 Typora 里写东西~",
  wps: "正在 WPS 里办公~",
  trello: "正在 Trello 里排任务~",
  todoist: "正在 Todoist 里排待办~",
  logseq: "正在 Logseq 里记笔记~",
  kindle: "正在 Kindle 里看书~",
  twitter: "正在刷 Twitter~",
  x: "正在刷 X~",
  weibo: "正在微博吃瓜~",
  xiaohongshu: "正在逛小红书~",
  zhihu: "正在知乎涨知识~",
  reddit: "正在 Reddit 冲浪~",
  github: "正在 GitHub 摸鱼~",
  instagram: "正在刷 Instagram~",
  facebook: "正在逛 Facebook~",
  pinterest: "正在 Pinterest 找灵感~",
  idm: "正在下载东西~",
  xunlei: "正在用迅雷下载~",
  onedrive: "正在 OneDrive 同步文件~",
  dropbox: "正在 Dropbox 同步文件~",
  teams: "正在 Teams 开会~",
  zoom: "正在 Zoom 开会~",
  "task manager": "正在看任务管理器~",
  settings: "正在调系统设置~",
  idle: "暂时离开一下~"
};

const titleTemplates = new Map<string, (title: string) => string>([
  ["vs code", (title) => `正在 VS Code 里改《${title}》~`],
  ["cursor", (title) => `正在 Cursor 里改《${title}》~`],
  ["visual studio", (title) => `正在 Visual Studio 里写《${title}》~`],
  ["intellij idea", (title) => `正在 IDEA 里写《${title}》~`],
  ["pycharm", (title) => `正在 PyCharm 里写《${title}》~`],
  ["webstorm", (title) => `正在 WebStorm 里写《${title}》~`],
  ["qq music", (title) => `正在 QQ 音乐里播放《${title}》~`],
  ["spotify", (title) => `正在 Spotify 里播放《${title}》~`],
  ["apple music", (title) => `正在 Apple Music 里播放《${title}》~`],
  ["google chrome", (title) => `正在 Chrome 里看《${title}》~`],
  ["microsoft edge", (title) => `正在 Edge 里看《${title}》~`],
  ["firefox", (title) => `正在 Firefox 里看《${title}》~`],
  ["safari", (title) => `正在看《${title}》~`],
  ["figma", (title) => `正在 Figma 里做《${title}》~`],
  ["photoshop", (title) => `正在 Photoshop 里处理《${title}》~`],
  ["vlc", (title) => `正在看《${title}》~`],
  ["potplayer", (title) => `正在 PotPlayer 里看《${title}》~`],
  ["steam", (title) => `正在 Steam 里玩《${title}》~`],
  ["word", (title) => `正在 Word 里写《${title}》~`],
  ["excel", (title) => `正在 Excel 里算《${title}》~`],
  ["powerpoint", (title) => `正在做《${title}》这份 PPT~`],
  ["notion", (title) => `正在 Notion 里整理《${title}》~`],
  ["obsidian", (title) => `正在 Obsidian 里写《${title}》~`],
  ["typora", (title) => `正在 Typora 里写《${title}》~`]
]);

const MUSIC_APPS = new Set(["spotify", "qq music", "apple music", "netease cloud music"]);

export function getAppDescription(appName: string, displayTitle?: string, music?: MusicPayload): string {
  const lower = appName.toLowerCase();

  if (displayTitle && !(music?.title && MUSIC_APPS.has(lower))) {
    const template = titleTemplates.get(lower);
    if (template) {
      return template(displayTitle);
    }

    return `正在处理《${displayTitle}》~`;
  }

  return descriptions[lower] || "正在忙别的事情~";
}

export function formatMusicLine(music?: MusicPayload): string | null {
  if (!music?.title) {
    return null;
  }

  return music.artist ? `${music.artist} - ${music.title}` : music.title;
}
